# Generated by Django 5.2.5 on 2025-08-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
